#服务端口号
server:
  port: 8004
#应用名
spring:
  application:
    name:  'service-acl'
#数据原配置
  datasource:
    url: 'jdbc:mysql://localhost:3306/education?serverTimezone=GMT%2B8'
    password: '123456'
    username: 'root'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
#服务注册配置
  cloud:
    nacos:
      discovery:
        server-addr: '127.0.0.1:8848'
  redis:
    port: 6379
    database: 0
    timeout: '1800000'
    lettuce:
      pool:
        max-active: 20
        max-wait:  '-1'
        max-idle: 5
        min-idle: 0
    host: '192.168.174.88'

#配置mybatis xml文件配置
mybatis-plus:
  mapper-locations: 'classpath:com/hbnu/cms/mapper/xml/*.xml'
  configuration:
    log-impl: 'org.apache.ibatis.logging.stdout.StdOutImpl'



