server:
  port: 8002
spring:
  profiles:
    active: 'dev'
  datasource:
    url: 'jdbc:mysql://localhost:3306/education?serverTimezone=GMT%2B8'
    password: '123456'
    username: 'root'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    jackson:
      date-format:  'yyyy-MM-dd HH:mm:ss'   #解决json传输时区问题
      time-zone:  'GMT+8'
  cloud:
    nacos:
      discovery:
        server-addr: '127.0.0.1:8848'
  redis:
    port: 6379
    database: 0
    timeout: '1800000'
    lettuce:
      pool:
        max-active: 20
        max-wait:  '-1'
        max-idle: 5
        min-idle: 0
    host: '192.168.174.88'

mybatis-plus:
  mapper-locations: 'com/hbnu/edu/mapper/xml/*.xml'

