#端口号 服务名 环境配置
server:
  port: 8082
spring:
  application:
    name: 'service-oss'
  profiles:
    active: dev
#阿里云云存储配置,地域节点，id ，密钥，库名
aliyun:
  oss:
    file:
      endpoint: 'oss-cn-chengdu.aliyuncs.com'
      keyid: 'LTAI4GAMY45Y4BVur2shCh1g'
      keysecret: 'dtvJAFr2RLTtiHMC7HNdQJHTsxhEQ7'
      bucketname: 'edu-storage1'
