#服务端口号
server:
  port: 8081


#服务名 环境配置 数据库链接
spring:
  application:
    name: 'service-teacher'
  profiles:
    active: 'dev'
  datasource:
    url: 'jdbc:mysql://localhost:3306/education?serverTimezone=GMT%2B8'
    password: '123456'
    username: 'root'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jackson:
    date-format:  'yyyy-MM-dd HH:mm:ss'   #解决时区问题
    time-zone:  'GMT+8'
#mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

