#服务端口号
server:
  port: 8081


#服务名 环境配置 数据库链接
spring:
  application:
    name: 'service-teacher'
  profiles:
    active: 'dev'
  datasource:
    url: 'jdbc:mysql://localhost:3306/education?serverTimezone=GMT%2B8'
    password: '123456'
    username: 'root'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jackson:
    date-format:  'yyyy-MM-dd HH:mm:ss'   #解决json传输时区问题
    time-zone:  'GMT+8'
#mybatis 日志
#mybatis-plus:
#  configuration:
#    log-impl: 'org.apache.ibatis.logging.stdout.StdOutImpl'

#日志显示设置
#logging:
#  level: 'debug'

#开始使用logback代替mybatis+自带的日志 配置logback-spring.xml 拷贝

#配置mybatis xml文件配置
mybatis-plus:
  mapper-locations: 'classpath:com/hbnu/edu/mapper/xml/*.xml'
