server:
  port: 8001
spring:
  application:
    name:  'service-msm'

  cloud:
    nacos:
      discovery:
        server-addr: '127.0.0.1:8848'
  profiles:
    active:  'dev'
  redis:
    port: 6379
    database: 0
    timeout: '1800000'
    lettuce:
      pool:
        max-active: 20
        max-wait:  '-1'
        max-idle: 5
        min-idle: 0
    host: '192.168.174.88'

aliyun:
  msm:
    file:
      keyid: 'LTAI4GAMY45Y4BVur2shCh1g'
      keysecret: 'dtvJAFr2RLTtiHMC7HNdQJHTsxhEQ7'